---
title: Цикл for зі списком у Python
hero_image: images/banner.png
description: Використання циклу for зі списком у Python
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "Python"
steps:
  - title: Цикл for зі списком
