---
title: For lus met een lijst in Python
hero_image: images/banner.png
description: Het gebruik van een for lus met een lijst in Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "Python"
steps:
  - 
    title: For lus met een lijst
