title: For loop over a list in Python
hero_image: images/banner.png
description: Using a for loop over a list in Python
original_url: 
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
interests: ""
technologies: "Python"
steps:
  - title: For loop over a list
