---
title: For-løkke med en liste i Python
hero_image: images/banner.png
description: Bruk en for-løkke med en liste i Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "Python"
steps:
  - 
    title: For-løkke med en liste
