---
title: Ciclo for com uma lista em Python
hero_image: images/banner.png
description: Usar um ciclo for com uma lista em Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "Python"
steps:
  - 
    title: Ciclo for com uma lista
