---
title: For petlja sa listom u Pythonu
hero_image: images/banner.png
description: Korištenje for petlje na listi u Pythonu
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "Python"
steps:
  - title: For petlja na listi
