---
title: For-Schleife mit einer Liste in Python
hero_image: images/banner.png
description: Eine for-Schleife auf eine Liste in Python anwenden
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "Python"
steps:
  - 
    title: For-Schleife mit einer Liste
