---
title: Fazer uma lista com loop for em Python
hero_image: images/banner.png
description: Utilizando o loop for para criar uma lista em Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "Python"
steps:
  - 
    title: Lista com loop for
