---
title: Bucle «for» en una lista de Python
hero_image: images/banner.png
description: Usar un bucle «for» en una lista de Python
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "Python"
steps:
  - title: Bucle «for» en una lista
