---
title: Bucle 'for' con una lista en Python
hero_image: images/banner.png
description: Usar un bucle 'for' con una lista en Python
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "Python"
steps:
  - 
    title: Bucle 'for' con una lista
