---
title: Pętla for z listą w Pythonie
hero_image: images/banner.png
description: Używanie pętli for z listą w Pythonie
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "Python"
steps:
  - 
    title: Pętla for z listą
