---
title: Για βρόχο με μια λίστα στην Python
hero_image: images/banner.png
description: Χρησιμοποιώντας έναν βρόχο "Για" με μια λίστα στην Python
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "Python"
steps:
  - 
    title: Βρόχος "Για" με μια λίστα
