---
title: Boucle for avec une liste en Python
hero_image: images/banner.png
description: Boucle for avec une liste en Python
original_url:
theme: cc-prototype
duration: 1 #1, 2 or 3
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "Python"
steps:
  - 
    title: Boucle for avec une liste
